# Generated by Django 5.2.8 on 2025-12-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], db_index=True, max_length=3)),
                ('msg_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('DOCUMENT', 'Document'), ('STICKER', 'Sticker'), ('LOCATION', 'Location'), ('INTERACTIVE', 'Interactive'), ('TEMPLATE', 'Template'), ('UNKNOWN', 'Unknown')], db_index=True, default='TEXT', max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('RECEIVED', 'Received'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=20)),
                ('waba_message_id', models.CharField(blank=True, db_index=True, help_text='WhatsApp Business API message ID (wamid).', max_length=191, null=True)),
                ('context_message_id', models.CharField(blank=True, help_text='Reply-to message ID (if this message is a reply).', max_length=191, null=True)),
                ('contact_phone', models.CharField(db_index=True, help_text='E.164 formatted phone number of the WhatsApp user.', max_length=20)),
                ('waba_phone_number_id', models.CharField(blank=True, help_text='The phone_number_id used to send/receive this message.', max_length=64, null=True)),
                ('body_text', models.TextField(blank=True, help_text='Primary text body if present (message body, caption, etc.).')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw WhatsApp message payload (normalized or original).')),
                ('error_code', models.CharField(blank=True, help_text='Error code returned by Meta (if any).', max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message returned by Meta (if any).', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, help_text='For inbound messages, when we stored it.', null=True)),
            ],
            options={
                'db_table': 'messaging_message_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['direction', 'status'], name='messaging_m_directi_b5ef8b_idx'), models.Index(fields=['contact_phone', 'created_at'], name='messaging_m_contact_4a03e0_idx'), models.Index(fields=['waba_message_id'], name='messaging_m_waba_me_023d4b_idx')],
            },
        ),
    ]
