# Generated by Django 5.2.8 on 2025-12-09 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='FK to Contact (if available).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='contacts.contact'),
        ),
    ]
