# Generated by Django 5.2.8 on 2025-12-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('messaging', '0002_messagelog_contact'),
        ('workspaces', '0002_alter_workspace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='waba_phone_number_id',
            field=models.CharField(blank=True, db_index=True, help_text='The phone_number_id used to send/receive this message.', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['workspace', 'contact_phone', 'created_at'], name='messaging_m_workspa_f5730e_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['workspace', 'direction', 'status'], name='messaging_m_workspa_4c6169_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagelog',
            constraint=models.UniqueConstraint(condition=models.Q(('waba_message_id__isnull', False)), fields=('workspace', 'waba_message_id'), name='uq_msglog_workspace_wamid'),
        ),
    ]
