# Generated by Django 5.2.8 on 2025-12-09 05:18

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=191)),
                ('phone', models.CharField(db_index=True, help_text='WhatsApp phone number in E.164 format, e.g. +919876543210', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format, e.g. +919876543210', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('language', models.CharField(db_index=True, default='en', help_text='Preferred language code (e.g. en, en_US, hi).', max_length=10)),
                ('timezone', models.CharField(blank=True, help_text='Optional IANA timezone (e.g. Asia/Kolkata).', max_length=64, null=True)),
                ('is_opted_out', models.BooleanField(default=False, help_text='If true, do not send broadcast / marketing messages.')),
                ('is_blocked', models.BooleanField(default=False, help_text='If true, skip any automated messages to this contact.')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time we received a message from this contact.', null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="Segment tags, e.g. ['lead', 'webinar', 'hot'].", size=None)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Any extra metadata (utm, crm_id, etc.).')),
            ],
            options={
                'db_table': 'contacts_contact',
                'ordering': ['full_name', 'phone'],
                'indexes': [models.Index(fields=['is_opted_out', 'is_blocked'], name='contacts_co_is_opte_708a9e_idx'), models.Index(fields=['language'], name='contacts_co_languag_325b54_idx')],
            },
        ),
    ]
