# Generated by Django 5.2.8 on 2025-12-25 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('workspaces', '0002_alter_workspace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='workspaces.workspace'),
        ),
    ]
