# Generated by Django 5.2.8 on 2025-12-24 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
        ('workspaces', '0002_alter_workspace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookeventlog',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stable idempotency key to prevent duplicate processing.', max_length=128),
        ),
        migrations.AddField(
            model_name='webhookeventlog',
            name='phone_number_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='webhookeventlog',
            name='provider',
            field=models.CharField(db_index=True, default='META_WHATSAPP', max_length=50),
        ),
        migrations.AddField(
            model_name='webhookeventlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='whatsappwebhookconfig',
            name='phone_number_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional: Meta phone_number_id to link this config to a number.', max_length=64),
        ),
        migrations.AddField(
            model_name='whatsappwebhookconfig',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_webhook_configs', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='webhookeventlog',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='whatsappwebhookconfig',
            name='verify_token',
            field=models.CharField(help_text='Verify token used in the webhook setup and GET challenge.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='webhookeventlog',
            index=models.Index(fields=['provider', 'created_at'], name='webhooks_we_provide_57ebca_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventlog',
            index=models.Index(fields=['processing_status', 'created_at'], name='webhooks_we_process_36c425_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventlog',
            index=models.Index(fields=['phone_number_id', 'created_at'], name='webhooks_we_phone_n_a4592d_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookeventlog',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('workspace', 'provider', 'dedupe_key'), name='uq_webhookevent_workspace_provider_dedupe'),
        ),
        migrations.AddConstraint(
            model_name='whatsappwebhookconfig',
            constraint=models.UniqueConstraint(fields=('workspace', 'verify_token'), name='uq_webhookcfg_workspace_verify_token'),
        ),
    ]
