# Generated by Django 5.2.8 on 2025-12-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_backfill_dedupe_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookeventlog',
            name='dedupe_key',
            field=models.CharField(db_index=True, help_text='Stable idempotency key to prevent duplicate processing.', max_length=128),
        ),
    ]
