# Generated by Django 5.2.8 on 2025-12-24 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_alter_webhookeventlog_dedupe_key'),
        ('workspaces', '0002_alter_workspace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappwebhookconfig',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_webhook_configs', to='workspaces.workspace'),
        ),
    ]
