# Generated by Django 5.2.8 on 2025-12-03 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=191)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID from Meta Business / Cloud API, if synced.', max_length=191, null=True)),
                ('namespace', models.CharField(blank=True, help_text='Template namespace from Meta (if provided).', max_length=191, null=True)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], db_index=True, max_length=32)),
                ('subtype', models.CharField(blank=True, db_index=True, help_text='Optional subtype: COUPON, CATALOG, MEDIA_CAROUSEL, CALL_PERMISSION, SPM, MPM, etc.', max_length=64, null=True)),
                ('language', models.CharField(db_index=True, default='en', help_text='BCP-47 language code (e.g. en, en_US, hi).', max_length=10)),
                ('auth_type', models.CharField(choices=[('NONE', 'None'), ('COPY_CODE', 'Copy code'), ('ONE_TAP', 'One-tap'), ('ZERO_TAP', 'Zero-tap')], default='NONE', help_text='For authentication templates: COPY_CODE, ONE_TAP, ZERO_TAP.', max_length=32)),
                ('body_text', models.TextField(blank=True, help_text='Primary body text with variables (for quick search / preview).')),
                ('components', models.JSONField(blank=True, default=dict, help_text='Full template components JSON (header/body/footer/buttons/carousels).')),
                ('variable_count', models.PositiveIntegerField(default=0, help_text='Number of template variables ({{1}}, {{2}}, ...).')),
                ('quality_rating', models.CharField(blank=True, help_text="Meta's quality rating: GREEN, YELLOW, RED, or similar.", max_length=32, null=True)),
                ('messaging_limit_tier', models.CharField(blank=True, help_text='Messaging limit tier for this template or WABA if applicable.', max_length=64, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISABLED', 'Disabled'), ('IN_APPEAL', 'In appeal')], db_index=True, default='PENDING', max_length=32)),
                ('is_paused', models.BooleanField(default=False, help_text='Whether sending using this template is currently paused.')),
                ('ttl_seconds', models.PositiveIntegerField(default=0, help_text='Optional TTL for template use (0 = not set / unlimited).')),
                ('group_key', models.CharField(blank=True, db_index=True, help_text="Logical group (e.g. 'onboarding_welcome') to group template variants.", max_length=191, null=True)),
                ('source', models.CharField(choices=[('META_SYNC', 'Synced from Meta'), ('LOCAL', 'Created in ConvoNest')], default='META_SYNC', max_length=32)),
                ('meta_raw', models.JSONField(blank=True, default=dict, help_text="Raw JSON metadata as returned by Meta's template APIs.")),
                ('previous_template', models.ForeignKey(blank=True, help_text='Previous version in a template evolution chain.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='templates.template')),
            ],
            options={
                'db_table': 'templates_template',
                'ordering': ['name', 'language'],
            },
        ),
        migrations.CreateModel(
            name='TemplateButtonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(help_text="Button order index as per Meta's components array.")),
                ('button_type', models.CharField(choices=[('QUICK_REPLY', 'Quick reply'), ('URL', 'URL'), ('PHONE', 'Phone'), ('COPY_CODE', 'Copy code'), ('ONE_TAP', 'One-tap'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('text', models.CharField(help_text='Button title/label as shown to the user.', max_length=191)),
                ('url', models.CharField(blank=True, help_text='For URL buttons / call-to-action links.', max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='templates.template')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['category', 'language'], name='templates_t_categor_47fa18_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['status', 'quality_rating'], name='templates_t_status_5f7a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['group_key', 'language'], name='templates_t_group_k_11a19f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('name', 'language')},
        ),
    ]
