# Generated by Django 5.2.8 on 2025-12-16 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatebuttonconfig',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='templatebuttonconfig',
            name='payload',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='body_text',
            field=models.TextField(blank=True, help_text='Primary body text with variables (for search/preview).'),
        ),
        migrations.AlterField(
            model_name='template',
            name='components',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='template',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='messaging_limit_tier',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='meta_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='template',
            name='previous_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='templates.template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='quality_rating',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISABLED', 'Disabled'), ('IN_APPEAL', 'In appeal')], db_index=True, default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='template',
            name='subtype',
            field=models.CharField(blank=True, db_index=True, help_text='Optional subtype: COUPON, CATALOG, MEDIA_CAROUSEL, CALL_PERMISSION, etc.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='ttl_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='template',
            name='variable_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='templatebuttonconfig',
            name='index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='templatebuttonconfig',
            name='text',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='templatebuttonconfig',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
