# Generated by Django 5.2.8 on 2025-12-12 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappBusinessAccount',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('meta_business_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('meta_raw', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsuid', models.CharField(max_length=128, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('wa_username', models.CharField(blank=True, max_length=64, null=True)),
                ('meta_raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappPhoneNumber',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('e164_number', models.CharField(help_text='+911234567890', max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('display_name_status', models.CharField(default='UNKNOWN', max_length=32)),
                ('rejection_reason', models.TextField(blank=True)),
                ('registered', models.BooleanField(default=False)),
                ('two_step_enabled', models.BooleanField(default=False)),
                ('test_number', models.BooleanField(default=False)),
                ('oba_status', models.CharField(default='UNKNOWN', max_length=32)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('meta_raw', models.JSONField(blank=True, default=dict)),
                ('waba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='whatsapp_accounts.whatsappbusinessaccount')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication'), ('SERVICE', 'Service')], max_length=32)),
                ('opened_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('meta_raw', models.JSONField(blank=True, default=dict)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='whatsapp_accounts.whatsappcontact')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='whatsapp_accounts.whatsappphonenumber')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappQrCode',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deep_link', models.URLField()),
                ('image_url', models.URLField()),
                ('default_message', models.CharField(blank=True, max_length=512)),
                ('meta_raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='whatsapp_accounts.whatsappphonenumber')),
                ('waba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='whatsapp_accounts.whatsappbusinessaccount')),
            ],
        ),
    ]
