# Generated by Django 5.2.8 on 2025-12-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappbusinessaccount',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappbusinessaccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
