# Generated by Django 5.2.8 on 2025-12-17 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_accounts', '0002_whatsappbusinessaccount_is_connected_and_more'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verify_token', models.CharField(max_length=128)),
                ('meta_user_id', models.CharField(blank=True, default='', max_length=64)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='whatsappbusinessaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappbusinessaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversations', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='whatsappqrcode',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_qr_codes', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='bsuid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='whatsappphonenumber',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsappphonenumber',
            name='e164_number',
            field=models.CharField(blank=True, default='', help_text='+911234567890', max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsappphonenumber',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='whatsappqrcode',
            name='default_message',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['workspace', 'phone'], name='whatsapp_ac_workspa_395b00_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['workspace', 'bsuid'], name='whatsapp_ac_workspa_4fc8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['workspace', 'phone_number'], name='whatsapp_ac_workspa_a91fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['workspace', 'contact'], name='whatsapp_ac_workspa_0377cc_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappphonenumber',
            index=models.Index(fields=['waba'], name='whatsapp_ac_waba_id_41fed6_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappphonenumber',
            index=models.Index(fields=['e164_number'], name='whatsapp_ac_e164_nu_eca47c_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappcontact',
            constraint=models.UniqueConstraint(fields=('workspace', 'bsuid'), name='uniq_workspace_bsuid'),
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='whatsapp_accounts.whatsappphonenumber'),
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='waba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='whatsapp_accounts.whatsappbusinessaccount'),
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_connections', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='whatsappconnection',
            index=models.Index(fields=['phone_number', 'is_active'], name='whatsapp_ac_phone_n_d43953_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconnection',
            index=models.Index(fields=['workspace', 'is_active'], name='whatsapp_ac_workspa_93ecb0_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('workspace',), name='uniq_active_whatsapp_connection_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='whatsappconnection',
            constraint=models.UniqueConstraint(fields=('workspace', 'phone_number'), name='uniq_workspace_phone_number_connection'),
        ),
    ]
