# Generated by Django 5.2.8 on 2025-12-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_accounts', '0003_whatsappconnection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconnection',
            name='verify_token',
            field=models.CharField(max_length=64),
        ),
    ]
